# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68a5b5b4306de3693b2a26c9bf08e58c9490c449b29fd00cd743d424f97e11215ee2366a3c4ba621fdb5c5c211a01d0188de5f2afc0850c6a5249720d9506b0a

test:
  secret_key_base: f866129f43901d032a8948cc3fea010d1d277d49ef2ecd34fe3c64f4bf2b5540bb5174518180a219fd57133ba67840eedc4c97f7e9fc7e45e91b349c8d963a48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
